// auth
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const SET_SESSION_STARTED = 'SET_SESSION_STARTED';
export const SET_SESSION_SUCCESS = 'SET_SESSION_SUCCESS';
export const SET_SESSION_FAILED = 'SET_SESSION_FAILED';
export const CHECK_AUTH_TOKEN = 'CHECK_AUTH_TOKEN';
export const REFRESH_AUTH_TOKEN_STARTED = 'REFRESH_AUTH_TOKEN_STARTED';
export const REFRESH_AUTH_TOKEN_SUCCESS = 'REFRESH_AUTH_TOKEN_SUCCESS';
export const REFRESH_AUTH_TOKEN_FAILED = 'REFRESH_AUTH_TOKEN_FAILED';
// register
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const CONFIRMATION_FAILED = 'CONFIRMATION_FAILED';
export const CONFIRMATION_STARTED = 'CONFIRMATION_STARTED';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const RESEND_CODE_FAILED = 'RESEND_CODE_FAILED';
export const RESEND_CODE_STARTED = 'RESEND_CODE_STARTED';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
// fetch
export const FETCH_YT_SONGS_STARTED = 'FETCH_YT_SONGS_STARTED';
export const FETCH_YT_SONGS_SUCCESS = 'FETCH_YT_SONGS_SUCCESS';
export const FETCH_YT_SONGS_FAILED = 'FETCH_YT_SONGS_FAILED';
export const FETCH_BC_SONGS_STARTED = 'FETCH_BC_SONGS_STARTED';
export const FETCH_BC_SONGS_SUCCESS = 'FETCH_BC_SONGS_SUCCESS';
export const FETCH_BC_SONGS_FAILED = 'FETCH_BC_SONGS_FAILED';
export const FETCH_BT_SONGS_STARTED = 'FETCH_BT_SONGS_STARTED';
export const FETCH_BT_SONGS_SUCCESS = 'FETCH_BT_SONGS_SUCCESS';
export const FETCH_BT_SONGS_FAILED = 'FETCH_BT_SONGS_FAILED';
//player
export const PLAYER_ADD_SINGLE_SONG_BEFORE = 'PLAYER_ADD_SINGLE_SONG_BEFORE';
export const PLAYER_ADD_SONG = 'PLAYER_ADD_SONG';
export const PLAYER_ADD_SINGLE_SONG_AFTER = 'PLAYER_ADD_SINGLE_SONG_AFTER';
export const PLAYER_ADD_MULTI_SONG_BEFORE = 'PLAYER_ADD_MULTI_SONG_BEFORE';
export const PLAYER_ADD_MULTI_SONG_AFTER = 'PLAYER_ADD_MULTI_SONG_AFTER';
export const PLAYER_SYNC_PLAYLIST = 'PLAYER_SYNC_PLAYLIST';
export const PLAYER_SYNC_CURRENT_SONG = 'PLAYER_SYNC_CURRENT_SONG';
export const PLAYER_CLEAR_SONGS = 'PLAYER_CLEAR_SONGS';
export const PLAYER_QUEUE_SONG = 'PLAYER_QUEUE_SONG';
// search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_END = 'SEARCH_END';
export const SEARCH_NO_REFRESH = 'SEARCH_NO_REFRESH';
export const SEARCH_REFRESH = 'SEARCH_REFRESH';
// home
export const HOME_NO_REFRESH = 'HOME_NO_REFRESH';
export const HOME_REFRESH = 'HOME_REFRESH';
// profile
export const PROFILE_UPDATE_STARTED = 'PROFILE_UPDATE_STARTED';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_READ_STARTED = 'PROFILE_READ_STARTED';
export const PROFILE_READ_FAILED = 'PROFILE_READ_FAILED';
export const PROFILE_READ_SUCCESS = 'PROFILE_READ_SUCCESS';
export const PROFILE_GET_CURRENT_STARTED = 'PROFILE_GET_CURRENT_STARTED';
export const PROFILE_GET_CURRENT_FAILED = 'PROFILE_GET_CURRENT_FAILED';
export const PROFILE_GET_CURRENT_SUCCESS = 'PROFILE_GET_CURRENT_SUCCESS';
// playlist
export const PLAYLIST_GET_STARTED = 'PLAYLIST_GET_STARTED';
export const PLAYLIST_GET_FAILED = 'PLAYLIST_GET_FAILED';
export const PLAYLIST_GET_SUCCESS =  'PLAYLIST_GET_SUCCESS';
export const PLAYLIST_GET_RECENT_STARTED = 'PLAYLIST_GET_RECENT_STARTED';
export const PLAYLIST_GET_RECENT_SUCCESS = 'PLAYLIST_GET_RECENT_SUCCESS';
export const PLAYLIST_GET_RECENT_FAILED = 'PLAYLIST_GET_RECENT_FAILED';
export const PLAYLIST_GET_CURRENT_STARTED = 'PLAYLIST_GET_CURRENT_STARTED';
export const PLAYLIST_GET_CURRENT_SUCCESS = 'PLAYLIST_GET_CURRENT_SUCCESS';
export const PLAYLIST_GET_CURRENT_FAILED = 'PLAYLIST_GET_CURRENT_FAILED';
export const PLAYLIST_CREATE_STARTED = 'PLAYLIST_CREATE_STARTED';
export const PLAYLIST_CREATE_FAILED = 'PLAYLIST_CREATE_FAILED';
export const PLAYLIST_CREATE_SUCCESS =  'PLAYLIST_CREATE_SUCCESS';
export const PLAYLIST_UPDATE_STARTED = 'PLAYLIST_UPDATE_STARTED';
export const PLAYLIST_UPDATE_FAILED = 'PLAYLIST_UPDATE_FAILED';
export const PLAYLIST_UPDATE_SUCCESS =  'PLAYLIST_UPDATE_SUCCESS';
export const PLAYLIST_DELETE_STARTED = 'PLAYLIST_DELETE_STARTED';
export const PLAYLIST_DELETE_FAILED = 'PLAYLIST_DELETE_FAILED';
export const PLAYLIST_DELETE_SUCCESS =  'PLAYLIST_DELETE_SUCCESS';
export const PLAYLIST_FOLLOW_STARTED = 'PLAYLIST_FOLLOW_STARTED';
export const PLAYLIST_FOLLOW_FAILED = 'PLAYLIST_FOLLOW_FAILED';
export const PLAYLIST_FOLLOW_SUCCESS =  'PLAYLIST_FOLLOW_SUCCESS';
export const PLAYLIST_CLEAR = 'PLAYLIST_CLEAR';
export const PLAYLIST_CURRENT_REFRESH = 'PLAYLIST_CURRENT_REFRESH';
export const PLAYLIST_CURRENT_NO_REFRESH = 'PLAYLIST_CURRENT_NO_REFRESH';
export const PLAYLIST_CURRENT_SET = 'PLAYLIST_CURRENT_SET';
export const PLAYLIST_RESET_MUST_RELOAD = 'PLAYLIST_RESET_MUST_RELOAD';
export const PLAYLIST_MUST_RELOAD = 'PLAYLIST_MUST_RELOAD';
// reset
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
export const FORGOT_PASSWORD_STARTED = 'FORGOT_PASSWORD_STARTED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const RESET_PASSWORD_STARTED = 'RESET_PASSWORD_STARTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';
// nav
export const NAV_SET_TAB = 'NAV_SET_TAB';
export const NAV_SET_SUBTAB = 'NAV_SET_SUBTAB';
export const NAV_RESET_TABS = 'NAV_RESET_TABS';
// library
export const LIBRARY_REFRESH = 'LIBRARY_REFRESH';
export const LIBRARY_NO_REFRESH = 'LIBRARY_NO_REFRESH';
// theme
export const THEME_GET_RECENT_STARTED = 'THEME_GET_RECENT_STARTED';
export const THEME_GET_RECENT_SUCCESS = 'THEME_GET_RECENT_SUCCESS';
export const THEME_GET_RECENT_FAILED = 'THEME_GET_RECENT_FAILED';
export const THEME_GET_CURRENT_STARTED = 'THEME_GET_CURRENT_STARTED';
export const THEME_GET_CURRENT_SUCCESS = 'THEME_GET_CURRENT_SUCCESS';
export const THEME_GET_CURRENT_FAILED = 'THEME_GET_CURRENT_FAILED';
export const THEME_GET_ALL_STARTED = 'THEME_GET_ALL_STARTED';
export const THEME_GET_ALL_SUCCESS = 'THEME_GET_ALL_SUCCESS';
export const THEME_GET_ALL_FAILED = 'THEME_GET_ALL_FAILED';
export const THEME_CREATE_STARTED = 'THEME_CREATE_STARTED';
export const THEME_CREATE_FAILED = 'THEME_CREATE_FAILED';
export const THEME_CREATE_SUCCESS =  'THEME_CREATE_SUCCESS';
export const THEME_UPDATE_STARTED = 'THEME_UPDATE_STARTED';
export const THEME_UPDATE_FAILED = 'THEME_UPDATE_FAILED';
export const THEME_UPDATE_SUCCESS =  'THEME_UPDATE_SUCCESS';
export const THEME_RESET_MUST_RELOAD = 'THEME_RESET_MUST_RELOAD';
export const THEME_MUST_RELOAD = 'THEME_MUST_RELOAD';
