// auth
export const CLEAR_SESSION = 'CLEAR_SESSION';
export const SET_SESSION_STARTED = 'SET_SESSION_STARTED';
export const SET_SESSION_SUCCESS = 'SET_SESSION_SUCCESS';
export const SET_SESSION_FAILED = 'SET_SESSION_FAILED';
export const CHECK_AUTH_TOKEN = 'CHECK_AUTH_TOKEN';
export const REFRESH_AUTH_TOKEN_STARTED = 'REFRESH_AUTH_TOKEN_STARTED';
export const REFRESH_AUTH_TOKEN_SUCCESS = 'REFRESH_AUTH_TOKEN_SUCCESS';
export const REFRESH_AUTH_TOKEN_FAILED = 'REFRESH_AUTH_TOKEN_FAILED';
// register
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_STARTED = 'REGISTER_STARTED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const CONFIRMATION_FAILED = 'CONFIRMATION_FAILED';
export const CONFIRMATION_STARTED = 'CONFIRMATION_STARTED';
export const CONFIRMATION_SUCCESS = 'CONFIRMATION_SUCCESS';
export const RESEND_CODE_FAILED = 'RESEND_CODE_FAILED';
export const RESEND_CODE_STARTED = 'RESEND_CODE_STARTED';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
// fetch
export const FETCH_YT_SONGS_STARTED = 'FETCH_YT_SONGS_STARTED';
export const FETCH_YT_SONGS_SUCCESS = 'FETCH_YT_SONGS_SUCCESS';
export const FETCH_YT_SONGS_FAILED = 'FETCH_YT_SONGS_FAILED';
export const FETCH_BC_SONGS_STARTED = 'FETCH_BC_SONGS_STARTED';
export const FETCH_BC_SONGS_SUCCESS = 'FETCH_BC_SONGS_SUCCESS';
export const FETCH_BC_SONGS_FAILED = 'FETCH_BC_SONGS_FAILED';
export const FETCH_BT_SONGS_STARTED = 'FETCH_BT_SONGS_STARTED';
export const FETCH_BT_SONGS_SUCCESS = 'FETCH_BT_SONGS_SUCCESS';
export const FETCH_BT_SONGS_FAILED = 'FETCH_BT_SONGS_FAILED';
//player
export const PLAYER_ADD_SINGLE_SONG_BEFORE = 'PLAYER_ADD_SINGLE_SONG_BEFORE';
export const PLAYER_ADD_SONG = 'PLAYER_ADD_SONG';
export const PLAYER_ADD_SINGLE_SONG_AFTER = 'PLAYER_ADD_SINGLE_SONG_AFTER';
export const PLAYER_ADD_MULTI_SONG_BEFORE = 'PLAYER_ADD_MULTI_SONG_BEFORE';
export const PLAYER_ADD_MULTI_SONG_AFTER = 'PLAYER_ADD_MULTI_SONG_AFTER';
export const PLAYER_SYNC_PLAYLIST = 'PLAYER_SYNC_PLAYLIST';
// search
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_END = 'SEARCH_END';
// profile
export const PROFILE_UPDATE_STARTED = 'PROFILE_UPDATE_STARTED';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_READ_STARTED = 'PROFILE_READ_STARTED';
export const PROFILE_READ_FAILED = 'PROFILE_READ_FAILED';
export const PROFILE_READ_SUCCESS = 'PROFILE_READ_SUCCESS';
// playlist
export const PLAYLIST_GET_STARTED = 'PLAYLIST_GET_STARTED';
export const PLAYLIST_GET_FAILED = 'PLAYLIST_GET_FAILED';
export const PLAYLIST_GET_SUCCESS =  'PLAYLIST_GET_SUCCESS';
export const PLAYLIST_GET_ID_STARTED = 'PLAYLIST_GET_STARTED';
export const PLAYLIST_GET_ID_FAILED = 'PLAYLIST_GET_ID_FAILED';
export const PLAYLIST_GET_ID_SUCCESS =  'PLAYLIST_GET_ID_SUCCESS';
export const PLAYLIST_GET_RECENT_STARTED = 'PLAYLIST_GET_RECENT_STARTED';
export const PLAYLIST_GET_RECENT_SUCCESS = 'PLAYLIST_GET_RECENT_SUCCESS';
export const PLAYLIST_GET_RECENT_FAILED = 'PLAYLIST_GET_RECENT_FAILED';
export const PLAYLIST_CREATE_STARTED = 'PLAYLIST_CREATE_STARTED';
export const PLAYLIST_CREATE_FAILED = 'PLAYLIST_CREATE_FAILED';
export const PLAYLIST_CREATE_SUCCESS =  'PLAYLIST_CREATE_SUCCESS';
export const PLAYLIST_UPDATE_STARTED = 'PLAYLIST_UPDATE_STARTED';
export const PLAYLIST_UPDATE_FAILED = 'PLAYLIST_UPDATE_FAILED';
export const PLAYLIST_UPDATE_SUCCESS =  'PLAYLIST_UPDATE_SUCCESS';
export const PLAYLIST_DELETE_STARTED = 'PLAYLIST_DELETE_STARTED';
export const PLAYLIST_DELETE_FAILED = 'PLAYLIST_DELETE_FAILED';
export const PLAYLIST_DELETE_SUCCESS =  'PLAYLIST_DELETE_SUCCESS';
export const PLAYLIST_FOLLOW_STARTED = 'PLAYLIST_FOLLOW_STARTED';
export const PLAYLIST_FOLLOW_FAILED = 'PLAYLIST_FOLLOW_FAILED';
export const PLAYLIST_FOLLOW_SUCCESS =  'PLAYLIST_FOLLOW_SUCCESS';
export const PLAYLIST_CLEAR = 'PLAYLIST_CLEAR';
